FROM registry.redhat.io/ubi9/nodejs-20-minimal:1-51 AS builder

WORKDIR /usr/src/app

ENV HUSKY=0

COPY package.json yarn.lock .
RUN npm install

COPY ./console-extensions.json ./tsconfig.json ./webpack.config.ts .
COPY ./locales ./locales
COPY ./src ./src
RUN npm run build

FROM registry.redhat.io/rhel9/nginx-120:1-148

USER 1001

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
